### ISSUE TITLE
module 'urllib' has no attribute 'request'

### ISSUE THREAD

**Issue by maxpowel** [HSE-asavchenko/hsemotion-onnx#1]
If you try a fresh environment and the basic example, you will get this error:

```
AttributeError: module 'urllib' has no attribute 'request'
```
and the error is located at `hsemotion_onnx/facial_emotions.py", line 23, in get_model_path`

**Comment by maxpowel** [comment]
I have just added a pull request that works with python 3.10+

**Comment by av-savchenko** [comment]
Great thanks, I merged your pool request. Moreover, I fixed the same issue for hsemotion repository

**Comment by maxpowel** [comment]
Great!
